- name: Install and configure nomad clients
  hosts: nomad-clients
  become: true
  user: ansible
  gather_facts: no
  become_method: sudo
  vars_files:
   - group_vars/all
  roles:
   - role: nomad-client
