- name: Install and configure nomad servers
  hosts: nomad-servers
  become: true
  user: ansible
  gather_facts: no
  become_method: sudo
  vars_files:
   - group_vars/all
  roles:
   - role: nomad-server
